In [37]:
import pandas as pd

In [38]:
jeet = pd.read_csv('data.csv')

In [39]:
jeet

                                               Sentence Sentiment
0     The GeoSolutions technology will leverage Bene...  positive
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2     For the last quarter of 2010 , Componenta 's n...  positive
3     According to the Finnish-Russian Chamber of Co...   neutral
4     The Swedish buyout firm has sold its remaining...   neutral
...                                                 ...       ...
5837  RISING costs have forced packaging producer Hu...  negative
5838  Nordic Walking was first used as a summer trai...   neutral
5839  According shipping company Viking Line , the E...   neutral
5840  In the building and home improvement trade , s...   neutral
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive

[5842 rows x 2 columns]

In [40]:
import re

In [41]:
def cleeen(tt):
    tt=tt.lower()#lowercase
    tt= re.sub(r'\d+','',tt)#remove digits
    tt=re.sub(r'[^\w\s]','',tt)#remove punctuation
    tt = re.sub(r'\s+',' ',tt)#remove extra spaces
    return tt
print(jeet.columns)

Index(['Sentence', 'Sentiment'], dtype='object')

In [42]:
jeet['cleeen']=jeet['Sentence'].apply(cleeen)
jeet[['Sentence', 'cleeen']]

,Sentence,cleeen
0,The GeoSolutions technology will leverage Bene...,the geosolutions technology will leverage bene...
1,"$ESI on lows, down $1.50 to $2.50 BK a real po...",esi on lows down to bk a real possibility
2,"For the last quarter of 2010 , Componenta 's n...",for the last quarter of componenta s net sales...
3,According to the Finnish-Russian Chamber of Co...,according to the finnishrussian chamber of com...
4,The Swedish buyout firm has sold its remaining...,the swedish buyout firm has sold its remaining...
...,...,...
5837,RISING costs have forced packaging producer Hu...,rising costs have forced packaging producer hu...
5838,Nordic Walking was first used as a summer trai...,nordic walking was first used as a summer trai...
5839,"According shipping company Viking Line , the E...",according shipping company viking line the eu ...
5840,"In the building and home improvement trade , s...",in the building and home improvement trade sal...
5841,HELSINKI AFX - KCI Konecranes said it has won ...,helsinki afx kci konecranes said it has won an...

In [43]:
#Word Tokenization
import nltk

In [44]:
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Jeet\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [45]:
jeet['tokenize'] = jeet['cleeen'].apply(word_tokenize)
jeet[['cleeen', 'tokenize']]

,cleeen,tokenize
0,the geosolutions technology will leverage bene...,"[the, geosolutions, technology, will, leverage..."
1,esi on lows down to bk a real possibility,"[esi, on, lows, down, to, bk, a, real, possibi..."
2,for the last quarter of componenta s net sales...,"[for, the, last, quarter, of, componenta, s, n..."
3,according to the finnishrussian chamber of com...,"[according, to, the, finnishrussian, chamber, ..."
4,the swedish buyout firm has sold its remaining...,"[the, swedish, buyout, firm, has, sold, its, r..."
...,...,...
5837,rising costs have forced packaging producer hu...,"[rising, costs, have, forced, packaging, produ..."
5838,nordic walking was first used as a summer trai...,"[nordic, walking, was, first, used, as, a, sum..."
5839,according shipping company viking line the eu ...,"[according, shipping, company, viking, line, t..."
5840,in the building and home improvement trade sal...,"[in, the, building, and, home, improvement, tr..."
5841,helsinki afx kci konecranes said it has won an...,"[helsinki, afx, kci, konecranes, said, it, has..."

In [51]:
# Stopword Removal
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jeet\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [53]:
from nltk.corpus import stopwords

In [54]:
stp= set(stopwords.words('english'))

In [55]:
#funtion to remove stopwords
def removestopwords(tkn):
    return [word for word in tkn if word not in stp]

In [56]:
jeet['filter'] = jeet['tokenize'].apply(removestopwords)

In [57]:
jeet[['tokenize', 'filter']]

,tokenize,filter
0,"[the, geosolutions, technology, will, leverage...","[geosolutions, technology, leverage, benefon, ..."
1,"[esi, on, lows, down, to, bk, a, real, possibi...","[esi, lows, bk, real, possibility]"
2,"[for, the, last, quarter, of, componenta, s, n...","[last, quarter, componenta, net, sales, double..."
3,"[according, to, the, finnishrussian, chamber, ...","[according, finnishrussian, chamber, commerce,..."
4,"[the, swedish, buyout, firm, has, sold, its, r...","[swedish, buyout, firm, sold, remaining, perce..."
...,...,...
5837,"[rising, costs, have, forced, packaging, produ...","[rising, costs, forced, packaging, producer, h..."
5838,"[nordic, walking, was, first, used, as, a, sum...","[nordic, walking, first, used, summer, trainin..."
5839,"[according, shipping, company, viking, line, t...","[according, shipping, company, viking, line, e..."
5840,"[in, the, building, and, home, improvement, tr...","[building, home, improvement, trade, sales, de..."
5841,"[helsinki, afx, kci, konecranes, said, it, has...","[helsinki, afx, kci, konecranes, said, order, ..."

In [58]:
#Stemming

In [59]:
from nltk.stem import PorterStemmer

In [61]:
stemmer = PorterStemmer()

In [63]:
jeet['filter'].apply(lambda tokens: [stemmer.stem(word) for word in tokens])

0       [geosolut, technolog, leverag, benefon, gp, so...
1                           [esi, low, bk, real, possibl]
2       [last, quarter, componenta, net, sale, doubl, ...
3       [accord, finnishrussian, chamber, commerc, maj...
4       [swedish, buyout, firm, sold, remain, percent,...
                              ...
5837    [rise, cost, forc, packag, produc, huhtamaki, ...
5838    [nordic, walk, first, use, summer, train, meth...
5839    [accord, ship, compani, vike, line, eu, decis,...
5840    [build, home, improv, trade, sale, decreas, eu...
5841    [helsinki, afx, kci, konecran, said, order, fo...
Name: filter, Length: 5842, dtype: object

In [64]:
jeet['Stem'] = jeet['filter'].apply(lambda tokens: [stemmer.stem(word) for word in tokens])

In [65]:
jeet[['filter', 'Stem']]

,filter,Stem
0,"[geosolutions, technology, leverage, benefon, ...","[geosolut, technolog, leverag, benefon, gp, so..."
1,"[esi, lows, bk, real, possibility]","[esi, low, bk, real, possibl]"
2,"[last, quarter, componenta, net, sales, double...","[last, quarter, componenta, net, sale, doubl, ..."
3,"[according, finnishrussian, chamber, commerce,...","[accord, finnishrussian, chamber, commerc, maj..."
4,"[swedish, buyout, firm, sold, remaining, perce...","[swedish, buyout, firm, sold, remain, percent,..."
...,...,...
5837,"[rising, costs, forced, packaging, producer, h...","[rise, cost, forc, packag, produc, huhtamaki, ..."
5838,"[nordic, walking, first, used, summer, trainin...","[nordic, walk, first, use, summer, train, meth..."
5839,"[according, shipping, company, viking, line, e...","[accord, ship, compani, vike, line, eu, decis,..."
5840,"[building, home, improvement, trade, sales, de...","[build, home, improv, trade, sale, decreas, eu..."
5841,"[helsinki, afx, kci, konecranes, said, order, ...","[helsinki, afx, kci, konecran, said, order, fo..."

In [66]:
#Count Vectorization or TF-IDF (Pickle Model)

In [67]:
import re
import pandas as pd
import numpy as np
import nltk
import pickle
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Download necessary NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# Step 1: Load Dataset
df = pd.read_csv("data.csv")

# Step 2: Clean Data using Regex
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove special characters and numbers
    return text

df["cleaned_text"] = df["Sentence"].apply(clean_text)

# Step 3: Word Tokenization
df["tokenized"] = df["cleaned_text"].apply(word_tokenize)

# Step 4: Stopword Removal
stop_words = set(stopwords.words("english"))
df["filtered"] = df["tokenized"].apply(lambda words: [w for w in words if w not in stop_words])

# Step 5: Stemming
stemmer = PorterStemmer()
df["stemmed"] = df["filtered"].apply(lambda words: [stemmer.stem(w) for w in words])

# Convert back to text
df["final_text"] = df["stemmed"].apply(lambda words: " ".join(words))

# Step 6: TF-IDF Vectorization
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["final_text"])

# Save the vectorizer
with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

# Encode Sentiment Labels
df["label"] = df["Sentiment"].map({"positive": 2, "neutral": 1, "negative": 0})

# Step 7: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, df["label"], test_size=0.2, random_state=42)

# Step 8: Train ML Model (Naïve Bayes)
model = MultinomialNB()
model.fit(X_train, y_train)

# Save the model
with open("sentiment_model.pkl", "wb") as f:
    pickle.dump(model, f)

# Model Evaluation
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Jeet\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jeet\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Model Accuracy: 66.64%